# Generated by Django 6.0.7 on 2026-08-25 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_type', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('font_family', models.CharField(max_length=200)),
                ('primary_color', models.CharField(max_length=200)),
                ('secondary_color', models.CharField(max_length=200)),
                ('background_color', models.CharField(max_length=200)),
                ('border_radius', models.IntegerField(blank=True, null=True)),
                ('content_width', models.IntegerField(blank=True, null=True)),
                ('content_height', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('font_color', models.CharField(max_length=200)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_type', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('calender', 'Calender'), ('forum', 'Forum'), ('lunch', 'Lunch'), ('quiz', 'Quiz'), ('learning Materials', 'Learning Materials'), ('school pictures', 'School Pictures'), ('careers', 'Careers'), ('ai chat', 'AI Chat'), ('classes', 'Classes'), ('grades', 'Grades')], max_length=200, unique=True)),
                ('code', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsMedium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media/cms')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=200)),
                ('alt_text', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockMedium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockMedia', to='cms.block')),
                ('medium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediumBlocks', to='cms.cmsmedium')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, null=True)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functionBlocks', to='cms.block')),
                ('function_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functionBlocks', to='cms.function')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('layout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.layout')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='cms.design')),
                ('layout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='cms.layout')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linksTo', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageBlocks', to='cms.block')),
                ('layout_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageBlocks', to='cms.layoutregion')),
                ('page_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageBlocks', to='cms.pageversion')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('page_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='cms.pageversion')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
