# Generated by Django 6.0.7 on 2026-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
