# Generated by Django 6.0.7 on 2026-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='background_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='font_family',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='primary_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='secondary_color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
