# Generated by Django 6.0.7 on 2026-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_design_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='font_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
