# Generated by Django 6.0.7 on 2026-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageversion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
