# Generated by Django 6.0.7 on 2026-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_pageversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Überschrift'), ('text', 'Text'), ('image', 'Bild'), ('button', 'Button'), ('function', 'Funktion')], max_length=50),
        ),
    ]
