# Generated by Django 6.0.7 on 2026-09-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_block_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='layout_region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageBlocks', to='cms.layoutregion'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
