# Generated by Django 6.0.7 on 2026-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_pageblock_layout_region_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmedium',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmsmedium',
            name='file',
            field=models.FileField(upload_to='cms/'),
        ),
    ]
