# Generated by Django 6.0.7 on 2026-09-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_blockmedium_position_alter_cmsmedium_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutregion',
            name='layout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cms.layout'),
        ),
        migrations.AddConstraint(
            model_name='layoutregion',
            constraint=models.UniqueConstraint(fields=('layout_id', 'key'), name='unique_region_key_per_layout'),
        ),
    ]
