# Generated by Django 6.0.7 on 2026-08-26 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_chat_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chat_ai',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='Message_ai',
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10),
        ),
    ]
